apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-db
spec:
  # La storageClass par défaut sera utilisée
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
