apiVersion: v1
kind: Pod
metadata:
  name: stress
  labels:
    app: stress
spec:
  containers:
  - name: stress
    image: polinux/stress:1.0.4
    # Lance 1 worker demandant 128Mi de RAM pendant 1 seconde
    args:
      - "stress"
      - "--vm"
      - "1"
      - "--vm-bytes"
      - "128M"
      - "--vm-hang"
      - "1"
    resources:
      requests:
        memory: 64Mi
        # Requis par le mutator google
        cpu: 50m
        ephemeral-storage: 100Mi
      limits:
        # Limite de mémoire max
        # Equivaut a définir le paramètre "memory.max" à 64Mi
        # au niveau du cgroups du conteneur
        memory: 64Mi
        # Requis par le mutator google
        cpu: 50m
        ephemeral-storage: 100Mi
---