apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_DB
              value: demo
            - name: POSTGRES_USER
              value: demo
            # mdp passé en env var
            # - name: POSTGRES_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: postgres
            - name: POSTGRES_PASSWORD_FILE
              value: /run/secrets/postgres/POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres
              mountPath: "/run/secrets/postgres"
              readOnly: true
      volumes:
        - name: postgres
          secret:
            secretName: postgres

